/*!COPYRIGHT HEADER! 
 *
 */

package com.darwino.demo.vaddin.hw.app;


import java.util.Hashtable;

import javax.servlet.Servlet;

import com.darwino.commons.Platform;
import com.darwino.commons.services.HttpServerContext;
import com.darwino.mobile.httpsrv.tjws.TJWSDarwinoHttpServer;
import com.darwino.mobile.httpsrv.tjws.TJWSHttpServer;


public class AppMobileServiceDispatcher extends TJWSDarwinoHttpServer {
	
	public AppMobileServiceDispatcher(HttpServerContext context) {
		super(context);
	}
	
	@Override
	protected TJWSHttpServer createHttpServer(final HttpServerContext serverContext, int port) {
		TJWSHttpServer srv = super.createHttpServer(serverContext, port);

		{
			// Context parameters
			if(!Platform.isDevelopment()) {
				srv.getInitParameters().put("productionMode", "true");
			}
		}
		
		{
			// Servlet parameters
			Hashtable<String, String> params = new Hashtable<String, String>();
			params.put("UI", "com.darwino.demo.vaddin.hw.app.HelloWorldVaadinUI");
			//params.put("widgetset", "com.darwino.demo.MyAppWidgetset");
	
			Servlet vaadinServlet = new com.vaadin.server.VaadinServlet();
			srv.addServlet(new String[]{"/app/*","/VAADIN/*"}, vaadinServlet, params, null);
		}
		
		return srv;
	}
	
	static void _refClasses() {
		Class<?> c = null;
		
		c = HelloWorldVaadinUI.class;

/*		
		71521450802479 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.ui.orderedlayout.VerticalLayoutStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.ui.orderedlayout.VerticalLayoutStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521464580594 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.ui.orderedlayout.VerticalLayoutStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.ui.orderedlayout.VerticalLayoutStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521468724477 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.ui.orderedlayout.VerticalLayoutStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.ui.orderedlayout.VerticalLayoutStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521471667051 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.VerticalLayoutStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.VerticalLayoutStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521476054736 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.VerticalLayoutStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.VerticalLayoutStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521479925542 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.VerticalLayoutStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.VerticalLayoutStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521483543159 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.ui.orderedlayout.AbstractOrderedLayoutStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.ui.orderedlayout.AbstractOrderedLayoutStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521486673720 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.ui.orderedlayout.AbstractOrderedLayoutStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.ui.orderedlayout.AbstractOrderedLayoutStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521489732277 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.ui.orderedlayout.AbstractOrderedLayoutStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.ui.orderedlayout.AbstractOrderedLayoutStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521492995803 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.AbstractOrderedLayoutStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.AbstractOrderedLayoutStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521498900978 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.AbstractOrderedLayoutStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.AbstractOrderedLayoutStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521503623765 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.AbstractOrderedLayoutStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.AbstractOrderedLayoutStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521508754253 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.ui.AbstractLayoutStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.ui.AbstractLayoutStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521512507224 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.ui.AbstractLayoutStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.ui.AbstractLayoutStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521517819456 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.ui.AbstractLayoutStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.ui.AbstractLayoutStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521523598118 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.AbstractLayoutStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.AbstractLayoutStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521528071149 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.AbstractLayoutStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.AbstractLayoutStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521532756444 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.AbstractLayoutStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.AbstractLayoutStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521549626526 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.AbstractComponentStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.AbstractComponentStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521568959061 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.AbstractComponentStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.AbstractComponentStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521578413229 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.AbstractComponentStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.AbstractComponentStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521583935361 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.AbstractComponentStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.AbstractComponentStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521590892680 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.AbstractComponentStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.AbstractComponentStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521595118646 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.AbstractComponentStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.AbstractComponentStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521599087345 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.communication.SharedStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.communication.SharedStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521603537588 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.communication.SharedStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.communication.SharedStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521607515257 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.communication.SharedStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.communication.SharedStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521610990783 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.SharedStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.SharedStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521616132456 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.SharedStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.SharedStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521621395817 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.SharedStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.SharedStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521625230965 [   15] WARN java.lang.Class: Class.forName() failed to load 'java.lang.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>java.lang.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521628576642 [   15] WARN java.lang.Class: Class.forName() failed to load 'java.lang.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>java.lang.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521632203627 [   15] WARN java.lang.Class: Class.forName() failed to load 'java.lang.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>java.lang.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521636279084 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521642436101 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521646485142 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521659347187 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.ui.orderedlayout.AbstractOrderedLayoutState$ChildComponentDataBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.ui.orderedlayout.AbstractOrderedLayoutState$ChildComponentDataBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521662937447 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.ui.orderedlayout.AbstractOrderedLayoutState$ChildComponentDataBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.ui.orderedlayout.AbstractOrderedLayoutState$ChildComponentDataBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521666817217 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.ui.orderedlayout.AbstractOrderedLayoutState$ChildComponentDataBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.ui.orderedlayout.AbstractOrderedLayoutState$ChildComponentDataBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521677102397 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.AbstractOrderedLayoutState$ChildComponentDataBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.AbstractOrderedLayoutState$ChildComponentDataBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521680351640 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.AbstractOrderedLayoutState$ChildComponentDataBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.AbstractOrderedLayoutState$ChildComponentDataBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521683619620 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.AbstractOrderedLayoutState$ChildComponentDataBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.AbstractOrderedLayoutState$ChildComponentDataBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521686831845 [   15] WARN java.lang.Class: Class.forName() failed to load 'java.lang.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>java.lang.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521690632381 [   15] WARN java.lang.Class: Class.forName() failed to load 'java.lang.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>java.lang.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521695178519 [   15] WARN java.lang.Class: Class.forName() failed to load 'java.lang.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>java.lang.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521698481228 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521702397385 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521706229612 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521711159817 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.ui.ui.UIStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.ui.ui.UIStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521714084554 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.ui.ui.UIStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.ui.ui.UIStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521717039955 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.ui.ui.UIStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.ui.ui.UIStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521720106782 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.UIStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.UIStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521723726602 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.UIStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.UIStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521726514778 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.UIStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.UIStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521729553269 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.ui.TabIndexStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.ui.TabIndexStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521732502855 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.ui.TabIndexStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.ui.TabIndexStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521735505855 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.ui.TabIndexStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.ui.TabIndexStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521738787217 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.TabIndexStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.TabIndexStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521741938118 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.TabIndexStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.TabIndexStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521745500520 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.TabIndexStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.TabIndexStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521750017817 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.AbstractComponentStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.AbstractComponentStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521753210161 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.AbstractComponentStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.AbstractComponentStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521756920051 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.AbstractComponentStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.AbstractComponentStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521762402011 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.AbstractComponentStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.AbstractComponentStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521769177147 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.AbstractComponentStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.AbstractComponentStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521773670962 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.AbstractComponentStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.AbstractComponentStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521779882528 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.communication.SharedStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.communication.SharedStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521786611034 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.communication.SharedStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.communication.SharedStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521790342420 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.communication.SharedStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.communication.SharedStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521793956135 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.SharedStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.SharedStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521798139198 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.SharedStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.SharedStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521801147622 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.SharedStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.SharedStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521804630848 [   15] WARN java.lang.Class: Class.forName() failed to load 'java.lang.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>java.lang.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521808513121 [   15] WARN java.lang.Class: Class.forName() failed to load 'java.lang.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>java.lang.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521812104173 [   15] WARN java.lang.Class: Class.forName() failed to load 'java.lang.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>java.lang.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521815235216 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521818423756 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521821598692 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521826136610 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.ui.ui.UIState$ReconnectDialogConfigurationStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.ui.ui.UIState$ReconnectDialogConfigurationStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521829327263 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.ui.ui.UIState$ReconnectDialogConfigurationStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.ui.ui.UIState$ReconnectDialogConfigurationStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521832209409 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.ui.ui.UIState$ReconnectDialogConfigurationStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.ui.ui.UIState$ReconnectDialogConfigurationStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521835531940 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.UIState$ReconnectDialogConfigurationStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.UIState$ReconnectDialogConfigurationStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521839347423 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.UIState$ReconnectDialogConfigurationStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.UIState$ReconnectDialogConfigurationStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521842563198 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.UIState$ReconnectDialogConfigurationStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.UIState$ReconnectDialogConfigurationStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521845495875 [   15] WARN java.lang.Class: Class.forName() failed to load 'java.lang.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>java.lang.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521848945939 [   15] WARN java.lang.Class: Class.forName() failed to load 'java.lang.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>java.lang.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521852541068 [   15] WARN java.lang.Class: Class.forName() failed to load 'java.lang.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>java.lang.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521857865181 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521875673231 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521882246773 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521887491237 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.ui.ui.UIState$PushConfigurationStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.ui.ui.UIState$PushConfigurationStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521891674190 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.ui.ui.UIState$PushConfigurationStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.ui.ui.UIState$PushConfigurationStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521895190968 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.ui.ui.UIState$PushConfigurationStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.ui.ui.UIState$PushConfigurationStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521899628135 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.UIState$PushConfigurationStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.UIState$PushConfigurationStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521903129310 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.UIState$PushConfigurationStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.UIState$PushConfigurationStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521906148588 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.UIState$PushConfigurationStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.UIState$PushConfigurationStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521909191463 [   15] WARN java.lang.Class: Class.forName() failed to load 'java.lang.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>java.lang.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521912319181 [   15] WARN java.lang.Class: Class.forName() failed to load 'java.lang.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>java.lang.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521915528269 [   15] WARN java.lang.Class: Class.forName() failed to load 'java.lang.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>java.lang.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521918578100 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521922075128 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521925525764 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521929519929 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.ui.ui.UIState$LocaleServiceStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.ui.ui.UIState$LocaleServiceStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521932887083 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.ui.ui.UIState$LocaleServiceStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.ui.ui.UIState$LocaleServiceStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521937591682 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.ui.ui.UIState$LocaleServiceStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.ui.ui.UIState$LocaleServiceStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521941034076 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.UIState$LocaleServiceStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.UIState$LocaleServiceStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521944612371 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.UIState$LocaleServiceStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.UIState$LocaleServiceStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521948163227 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.UIState$LocaleServiceStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.UIState$LocaleServiceStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521952510259 [   15] WARN java.lang.Class: Class.forName() failed to load 'java.lang.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>java.lang.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521957342161 [   15] WARN java.lang.Class: Class.forName() failed to load 'java.lang.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>java.lang.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521961935728 [   15] WARN java.lang.Class: Class.forName() failed to load 'java.lang.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>java.lang.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521965415391 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521969736997 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521973640831 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521984352751 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.ui.ui.PageStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.ui.ui.PageStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521989567734 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.ui.ui.PageStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.ui.ui.PageStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521993334542 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.ui.ui.PageStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.ui.ui.PageStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71521998097751 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.PageStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.PageStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522001677966 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.PageStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.PageStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522005484978 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.PageStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.PageStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522008552193 [   15] WARN java.lang.Class: Class.forName() failed to load 'java.lang.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>java.lang.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522011850016 [   15] WARN java.lang.Class: Class.forName() failed to load 'java.lang.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>java.lang.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522015182464 [   15] WARN java.lang.Class: Class.forName() failed to load 'java.lang.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>java.lang.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522018525848 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522022849527 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522026065128 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522029945426 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.ui.ui.UIState$NotificationTypeConfigurationBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.ui.ui.UIState$NotificationTypeConfigurationBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522033988578 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.ui.ui.UIState$NotificationTypeConfigurationBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.ui.ui.UIState$NotificationTypeConfigurationBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522039030409 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.ui.ui.UIState$NotificationTypeConfigurationBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.ui.ui.UIState$NotificationTypeConfigurationBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522048244358 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.UIState$NotificationTypeConfigurationBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.UIState$NotificationTypeConfigurationBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522055092323 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.UIState$NotificationTypeConfigurationBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.UIState$NotificationTypeConfigurationBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522064475909 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.UIState$NotificationTypeConfigurationBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.UIState$NotificationTypeConfigurationBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522068526953 [   15] WARN java.lang.Class: Class.forName() failed to load 'java.lang.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>java.lang.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522073718896 [   15] WARN java.lang.Class: Class.forName() failed to load 'java.lang.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>java.lang.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522077890072 [   15] WARN java.lang.Class: Class.forName() failed to load 'java.lang.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>java.lang.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522082451857 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522086947401 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522091674045 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522096819521 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.ui.ui.UIState$LoadingIndicatorConfigurationStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.ui.ui.UIState$LoadingIndicatorConfigurationStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522101587874 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.ui.ui.UIState$LoadingIndicatorConfigurationStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.ui.ui.UIState$LoadingIndicatorConfigurationStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522106259690 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.ui.ui.UIState$LoadingIndicatorConfigurationStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.ui.ui.UIState$LoadingIndicatorConfigurationStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522110279480 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.UIState$LoadingIndicatorConfigurationStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.UIState$LoadingIndicatorConfigurationStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522114343068 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.UIState$LoadingIndicatorConfigurationStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.UIState$LoadingIndicatorConfigurationStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522117536818 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.UIState$LoadingIndicatorConfigurationStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.UIState$LoadingIndicatorConfigurationStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522120777429 [   15] WARN java.lang.Class: Class.forName() failed to load 'java.lang.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>java.lang.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522124123986 [   15] WARN java.lang.Class: Class.forName() failed to load 'java.lang.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>java.lang.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522127369438 [   15] WARN java.lang.Class: Class.forName() failed to load 'java.lang.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>java.lang.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522130737301 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522134035595 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522137895824 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522143680525 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.ui.ui.UIState$TooltipConfigurationStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.ui.ui.UIState$TooltipConfigurationStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522148923295 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.ui.ui.UIState$TooltipConfigurationStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.ui.ui.UIState$TooltipConfigurationStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522153090389 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.ui.ui.UIState$TooltipConfigurationStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.ui.ui.UIState$TooltipConfigurationStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522156361727 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.UIState$TooltipConfigurationStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.UIState$TooltipConfigurationStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522159386742 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.UIState$TooltipConfigurationStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.UIState$TooltipConfigurationStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522162881611 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.UIState$TooltipConfigurationStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.UIState$TooltipConfigurationStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522166181945 [   15] WARN java.lang.Class: Class.forName() failed to load 'java.lang.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>java.lang.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522170578303 [   15] WARN java.lang.Class: Class.forName() failed to load 'java.lang.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>java.lang.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522175543433 [   15] WARN java.lang.Class: Class.forName() failed to load 'java.lang.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>java.lang.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522180328069 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522185373083 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522190246247 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522198329553 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.ui.ui.UIState$LocaleDataBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.ui.ui.UIState$LocaleDataBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522204855373 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.ui.ui.UIState$LocaleDataBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.ui.ui.UIState$LocaleDataBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522215649555 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.ui.ui.UIState$LocaleDataBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.ui.ui.UIState$LocaleDataBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522222423250 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.UIState$LocaleDataBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.UIState$LocaleDataBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522228669915 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.UIState$LocaleDataBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.UIState$LocaleDataBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522233231937 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.UIState$LocaleDataBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.UIState$LocaleDataBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522238147415 [   15] WARN java.lang.Class: Class.forName() failed to load 'java.lang.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>java.lang.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522243273397 [   15] WARN java.lang.Class: Class.forName() failed to load 'java.lang.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>java.lang.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522248563831 [   15] WARN java.lang.Class: Class.forName() failed to load 'java.lang.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>java.lang.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522252942507 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522257762897 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522262609372 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522268810800 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.ui.button.ButtonStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.ui.button.ButtonStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522272141712 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.ui.button.ButtonStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.ui.button.ButtonStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522275060573 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.ui.button.ButtonStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.ui.button.ButtonStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522278018783 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.ButtonStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.ButtonStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522280924127 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.ButtonStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.ButtonStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522286775237 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.ButtonStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.ButtonStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522290251510 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.ui.TabIndexStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.ui.TabIndexStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522297330334 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.ui.TabIndexStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.ui.TabIndexStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522304266919 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.ui.TabIndexStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.ui.TabIndexStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522309239194 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.TabIndexStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.TabIndexStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522316713523 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.TabIndexStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.TabIndexStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522331268040 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.TabIndexStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.TabIndexStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522359616925 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.AbstractComponentStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.AbstractComponentStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522366868404 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.AbstractComponentStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.AbstractComponentStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522371453213 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.AbstractComponentStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.AbstractComponentStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522381088615 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.AbstractComponentStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.AbstractComponentStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522388400984 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.AbstractComponentStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.AbstractComponentStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522391919063 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.AbstractComponentStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.AbstractComponentStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522395507845 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.communication.SharedStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.communication.SharedStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522399756575 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.communication.SharedStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.communication.SharedStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522403739380 [   15] WARN java.lang.Class: Class.forName() failed to load 'com.vaadin.shared.communication.SharedStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>com.vaadin.shared.communication.SharedStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522409659248 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.SharedStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.SharedStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522415850620 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.SharedStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.SharedStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522423269742 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.SharedStateBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.SharedStateBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522431033247 [   15] WARN java.lang.Class: Class.forName() failed to load 'java.lang.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>java.lang.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522435154936 [   15] WARN java.lang.Class: Class.forName() failed to load 'java.lang.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>java.lang.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522438783686 [   15] WARN java.lang.Class: Class.forName() failed to load 'java.lang.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>java.lang.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522442067351 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522445486835 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
		71522449839386 [   15] WARN java.lang.Class: Class.forName() failed to load 'sun.beans.infos.ObjectBeanInfo'. Use the -forcelinkclasses command line option or add <forceLinkClasses><pattern>sun.beans.infos.ObjectBeanInfo</pattern></forceLinkClasses> to your robovm.xml file to link it in.
*/
	}
}
